name: Laravel CI

on:
  push:
    branches: [ "main" ] # или ваша рабочая ветка

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, curl, intl, zip, fileinfo
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --no-interaction --force

      - name: Run tests
        run: php artisan test
